// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6bmofN8AKTuF_CTzztvYV-669H_Rekt0',
    appId: '1:102987602784:web:6db3a7ac16cb35320fdc05',
    messagingSenderId: '102987602784',
    projectId: 'fir-46e56',
    authDomain: 'fir-46e56.firebaseapp.com',
    databaseURL: 'https://fir-46e56-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-46e56.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6h2EhdXJ5ghzIz7-V_-ah0Zlgaa7oA4c',
    appId: '1:102987602784:android:69246059a25b33a80fdc05',
    messagingSenderId: '102987602784',
    projectId: 'fir-46e56',
    databaseURL: 'https://fir-46e56-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-46e56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbu5P6VrPANGW4X9qtxWL2s18-FQIF62I',
    appId: '1:102987602784:ios:08502bc9af16f99f0fdc05',
    messagingSenderId: '102987602784',
    projectId: 'fir-46e56',
    databaseURL: 'https://fir-46e56-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-46e56.firebasestorage.app',
    iosClientId: '102987602784-ob9o4sjouabb6rpvf0ipn55emh5963db.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

}